### ISSUE TITLE
Connector not working with Tableau 2019.2

### ISSUE THREAD

**Issue by cyberoner1** [ParFlesh/zabbix-wdc#2]
Hi,
maybe I do something wrong, but when I try to connect to Zabbix through wdc I am getting following error:

{"code":0,"data":"","message":""}

Any Idea what this means?

**Comment by ParFlesh** [comment]
If this is happening on the initial connect page, then it is most likely an invalid URL to the zabbix api.

**Comment by cyberoner1** [comment]
Sorry, but URL is correct and Username Password, too. I checked the URL via curl and there it is working without any issues

**Comment by cyberoner1** [comment]
was able to fix it. Had to add the URL of the Server into the Windows hosts
