### ISSUE TITLE
Zabbix history table not working with tableau

### ISSUE THREAD

**Issue by cyberoner1** [ParFlesh/zabbix-wdc#3]
Hi,
when I am connecting with tableau 2019.2.3 to Zabbix, the host and Item table is working. trying to add the history table I am getting following error:

`Error` creating object for class TableInfo. The input data for one of the contained objects is invalid. Either invalid data are present or required fields are empty for class ColumnInfo. Required fields and respective data types are: { (Name : 'id', Type : QString, IsRequired : true), (Name : 'dataType', Type : QString, IsRequired : true), (Name : 'alias', Type : QString, IsRequired : false), (Name : 'hidden', Type : bool, IsRequired : false), (Name : 'description', Type : QString, IsRequired : false), (Name : 'isPrimaryKey', Type : bool, IsRequired : false), (Name : 'foreignKey', Type : QVariantMap, IsRequired : false), (Name : 'columnRole', Type : QString, IsRequired : false), (Name : 'columnType', Type : QString, IsRequired : false), (Name : 'aggType', Type : QString, IsRequired : false), (Name : 'geoRole', Type : QString, IsRequired : false), (Name : 'defaultFormat', Type : QVariantMap, IsRequired : false), (Name : 'filterable', Type : bool, IsRequired : false) }`

any Idea what the Problem is?

**Comment by ParFlesh** [comment]
This is now implemented with https://github.com/ParFlesh/zabbix-wdc/pull/4

**Comment by cyberoner1** [comment]
thank you. it is working now,
