### ISSUE TITLE
where i can find submitConnector() function.

### ISSUE THREAD

**Issue by chetan4975** [ParFlesh/zabbix-wdc#5]
Not able to locate the source for submitConnector() from html page.

Checked with the below Sources-

		<script type="text/javascript" charset="utf-8" src="https://parflesh.github.io/jpZabbix/jpZabbix.js"></script>
		<script src="https://www.promisejs.org/polyfills/promise-7.0.4.min.js"></script>
		<script src="https://connectors.tableau.com/libs/tableauwdc-2.0.latest.js" type="text/javascript"></script>

**Comment by ParFlesh** [comment]
The submitConnector function is in the index.js file.  It is loaded in the next line after the tableauwdc lib.

https://github.com/ParFlesh/zabbix-wdc/blob/master/index.js#L268

**Comment by chetan4975** [comment]
Really appreciate your quick response.!
When you have added all the needed api calls/tables click Submit. If there are no errors you will be sent to Tableau's Data Source configuration page.

Tableau's Data Source configuration page it will be in browser or in Tableau application.?

**Comment by ParFlesh** [comment]
It will be in the Tableau application.  

In the Tableau application, when adding a data source.  Select "Web Data Connector" under "To a Server".  Then enter `https://parflesh.github.io/zabbix-wdc/index.html` in the url bar.

Then you will be able to connect and add the api calls.

You can also test and debug using the [Tableau Web Data Connector SDK](https://tableau.github.io/webdataconnector/)
