### ISSUE TITLE
Not an Issue but information needed

### ISSUE THREAD

**Issue by vanimesh** [ParFlesh/zabbix-wdc#8]
Hi,

Is there any place where we need to configure the tableau URL to send the data? Or only tableau end(WDC) should be configured?

**Comment by vanimesh** [comment]
Any update would really help me to integrate zabbix to tableau :-)

**Comment by ParFlesh** [comment]
If you use the GitHub pages hosted version, you only need to start with adding the WDC to tableau.  But, you can also host the app yourself locally on an Apache or nginx web server.

**Comment by vanimesh** [comment]
Hi Parflesh, thank you for your reply, it was very much in time and thanks for your kind help. Yes, i have hosted the pages it on our local webserver. I was able to authenticate and add the API calls. But what next? Do I need to now proceed to configure wdc in tableau? Or does it require any other configuration to be done in the files at the Zabbix end(like adding the tableau URL to send the data)?

Waiting for your reply :-)

**Comment by ParFlesh** [comment]
After you have added the api calls, you should be able to submit the form and be taken to the data source configuration page.

**Comment by ParFlesh** [comment]
All these steps should be done in tableau desktop once the web page is running.

**Comment by vanimesh** [comment]
Yes i am able to submit the form in zabbix. So the next steps are to create the WDC in tableau if i am not wrong. Please do correct me if i am wrong.

**Comment by ParFlesh** [comment]
Yes

**Comment by vanimesh** [comment]
Great it seems to work :-) . Thank you very much for your prompt response ParFlesh

**Comment by vanimesh** [comment]
Last thing. Does it generate any logs ?

**Comment by ParFlesh** [comment]
Unfortunately, the only logging that is useful is available with the WDC debug tool.

**Comment by vanimesh** [comment]
Successfully implemented this :-) thank you very much.

**Comment by ParFlesh** [comment]
Glad this was able to help you.

**Comment by vanimesh** [comment]
But lot of effort to build the params. Do you have a y readymade params ?
